package com.telmex.sipac.ui.view.catalog;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ExternalCompanies extends VerticalLayout {
	protected ComboBox<java.lang.String> cboCompany;
	protected TextField txtProvider;
	protected Button btnCancel;
	protected Button btnSearch;
	protected Label lblTotalRecords;
	protected Button btnAdd;

	public ExternalCompanies() {
		Design.read(this);
	}
}
