package com.telmex.sipac.ui.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Main extends VerticalLayout {
	protected Label lblUserName;
	protected Button btnHelp;
	protected Button btnLogout;
	protected CssLayout menu;
	protected Button btnDashboard;
	protected Button btnRequest;
	protected Button btnExitPass;
	protected Button btnComplain;
	protected Button btnDangerousWork;
	protected VerticalLayout content;

	public Main() {
		Design.read(this);
	}
}
